Repository AutoInvestor/users, pull requests merged in 2025-03, with the labels that each got.

#2 feat: add CI workflows for github actions
  .github/workflows/post-commit-pipeline.yml
  .github/workflows/pull-request-pipeline.yml
  .gitignore
Labels: major

#3 fix: solve issue when there is no tag for github workflow post commit
  .github/workflows/post-commit-pipeline.yml
Labels: major

#4 fix: no tags does not publish a correct version
  .github/workflows/post-commit-pipeline.yml
Labels: major

#5 feat: publish package to github
  .github/workflows/post-commit-pipeline.yml
Labels: major

#6 fix: revert the publish of the package to github
  .github/workflows/post-commit-pipeline.yml
Labels: major

#7 feat: pre-release version 0.0.1
  .github/workflows/post-commit-pipeline.yml
Labels: patch

#8 feat: publish to dockerhub
  .github/workflows/post-commit-pipeline.yml
  Dockerfile
Labels: patch

#9 feat: add linter spotless for java
  .github/workflows/post-commit-pipeline.yml
  .github/workflows/pull-request-pipeline.yml
  build.gradle
  config/eclipse-java-formatter.xml
  src/main/java/io/autoinvestor/users/UsersApplication.java
  src/test/java/io/autoinvestor/users/UsersApplicationTests.java
Labels: patch

#12 fix: solve issue when committing to CD repository with 'sed'
  .github/workflows/post-commit-pipeline.yml
Labels: patch

#13 fix: use PAT to commit to other repositories
  .github/workflows/post-commit-pipeline.yml
Labels: patch

#15 feat: bump patch version
  .github/workflows/post-commit-pipeline.yml
Labels: patch

#16 Feature/register login
  build.gradle
  src/main/java/io/autoinvestor/application/LoginUseCase/LoginCommand.java
  src/main/java/io/autoinvestor/application/LoginUseCase/LoginCommandHandler.java
  src/main/java/io/autoinvestor/application/LoginUseCase/UnauthorizedPassword.java
  src/main/java/io/autoinvestor/application/PasswordService.java
  src/main/java/io/autoinvestor/application/RegisterUserCommand.java
  src/main/java/io/autoinvestor/application/RegisterUserCommandHandler.java
  src/main/java/io/autoinvestor/application/RegisterUserUseCase/RegisterUserCommand.java
  src/main/java/io/autoinvestor/application/RegisterUserUseCase/RegisterUserCommandHandler.java
  src/main/java/io/autoinvestor/application/RegisterUserUseCase/UserRegisteredAlreadyExists.java
  src/main/java/io/autoinvestor/application/UserPasswordReadModel.java
  src/main/java/io/autoinvestor/application/UserRegistredReadModel.java
  src/main/java/io/autoinvestor/domain/AggregateRoot.java
  src/main/java/io/autoinvestor/domain/UserRepository.java
  src/main/java/io/autoinvestor/domain/users/InvalidPasswordLength.java
  src/main/java/io/autoinvestor/domain/users/User.java
  src/main/java/io/autoinvestor/domain/users/UserEmail.java
  src/main/java/io/autoinvestor/domain/users/UserPassword.java
  src/main/java/io/autoinvestor/domain/users/UserState.java
  src/main/java/io/autoinvestor/domain/users/UserWasRegisteredEvent.java
  src/main/java/io/autoinvestor/domain/users/UserWasRegisteredEventPayload.java
  src/main/java/io/autoinvestor/exceptions/EmailNotValid.java
  src/main/java/io/autoinvestor/infrastructure/InMemoryUserRepository.java
  src/main/java/io/autoinvestor/infrastructure/UserPasswordReadModel.java
  src/main/java/io/autoinvestor/infrastructure/UserRegisteredReadModel.java
  src/main/java/io/autoinvestor/infrastructure/UsersProjection.java
  src/main/java/io/autoinvestor/ui/GlobalExceptionHandler.java
  src/main/java/io/autoinvestor/ui/RegisterUserController.java
  src/main/java/io/autoinvestor/ui/UserDTO.java
Labels: major

#18 Feature/login
  src/main/java/io/autoinvestor/application/LoginUseCase/LoginCommandHandler.java
  src/main/java/io/autoinvestor/application/LoginUseCase/LoginUserNotFound.java
  src/main/java/io/autoinvestor/domain/users/UserPassword.java
  src/main/java/io/autoinvestor/infrastructure/UserPasswordReadModel.java
  src/main/java/io/autoinvestor/infrastructure/UsersProjection.java
  src/main/java/io/autoinvestor/ui/GlobalExceptionHandler.java
  src/main/java/io/autoinvestor/ui/LoginUser/LoginUserController.java
  src/main/java/io/autoinvestor/ui/LoginUser/LoginUserDTO.java
  src/main/java/io/autoinvestor/ui/RegisterUser/RegisterUserController.java
  src/main/java/io/autoinvestor/ui/RegisterUser/RegisterUserDTO.java
Labels: major

#20 AIR-9 Update helm values
  .github/workflows/post-commit-pipeline.yml
Labels: minor

#22 AIR-9 fix2:Update helm values
  .github/workflows/post-commit-pipeline.yml
Labels: minor

#23 AIR-10 Build docker image with BuildPacks
  .github/workflows/post-commit-pipeline.yml
  Dockerfile
  build.gradle
Labels: minor
